use crate::{
    Real,
    automation::AutomationTrack,
    id::{IdContainer, NumericId},
    incremental_id,
};

incremental_id! {
    /// Handle to an automation track in an [`AutomationTimeline`].
    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct AutomationId(u32) impl { NumericId };
}

#[derive(Debug, Clone)]
struct TrackData {
    track: AutomationTrack,
}

/// A group of automation tracks.
///
/// ```no_run
/// # use taudio::automation::AutomationTimeline;
/// #
/// let mut timeline = AutomationTimeline::new();
///
/// let frequency_track = timeline.register(...);
/// let volume_track = timeline.register(...);
///
/// // ...
///
/// let frequency = timeline.query_value(frequency_track, 23.0);
/// let volume = timeline.query_value(volume_track, 37.0);
/// ```
#[derive(Debug, Clone)]
pub struct AutomationTimeline {
    tracks: IdContainer<Vec<TrackData>>,
}

impl Default for AutomationTimeline {
    #[inline]
    fn default() -> Self {
        Self::new()
    }
}

impl AutomationTimeline {
    /// Constructs an empty timeline.
    #[inline]
    pub fn new() -> Self {
        Self {
            tracks: vec![].into(),
        }
    }

    /// Registers a new automation parameter with the given name.
    pub fn register(&mut self, track: AutomationTrack) -> AutomationId {
        self.tracks.push_id(TrackData { track })
    }

    pub fn get_track(&self, id: AutomationId) -> Option<&AutomationTrack> {
        self.tracks.get(id.as_index()).map(|t| &t.track)
    }

    pub fn get_track_mut(&mut self, id: AutomationId) -> Option<&mut AutomationTrack> {
        self.tracks.get_mut(id.as_index()).map(|t| &mut t.track)
    }

    /// Queries the value of the automation associated with the given id at the specified
    /// sample offset.
    ///
    /// # Panics
    /// Panics if an automation with the given id doesn't exist. This can only happen if
    /// an id generated by a different timeline is used.
    pub fn query_value(&self, id: AutomationId, offset: Real) -> Real {
        let data = &self.tracks[id];

        data.track.query_value(offset, Real::NAN)
    }
}
#[cfg(test)]
mod test {
    use crate::id::IncrementalId;

    use super::*;

    #[test]
    fn get_track_and_mut() {
        let mut timeline = AutomationTimeline::new();
        let id = timeline.register(AutomationTrack::new());

        let track = timeline.get_track(id);
        assert!(
            track.is_some(),
            "Track should exist for a newly registered ID"
        );

        let track_mut = timeline.get_track_mut(id);
        assert!(
            track_mut.is_some(),
            "Mutable track should exist for a newly registered ID"
        );
    }

    #[test]
    fn get_track_invalid_id() {
        let timeline = AutomationTimeline::new();

        let invalid_id = AutomationId::FIRST.next().next().next();

        assert!(timeline.get_track(invalid_id).is_none());
    }

    #[test]
    #[should_panic]
    fn query_value_invalid_id_panics() {
        let timeline = AutomationTimeline::new();
        let invalid_id = AutomationId::FIRST.next().next().next();

        let _ = timeline.query_value(invalid_id, 100.0);
    }
}
