use std::collections::HashMap;

use crate::{
    automation::AutomationTrack,
    id::{IdContainer, NumericId},
    incremental_id,
};

incremental_id! {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct AutomationId(u32) impl { NumericId };
}

#[derive(Debug, Clone)]
struct TrackData {
    track: AutomationTrack,
}

#[derive(Debug, Clone)]
pub struct AutomationTimeline {
    tracks: IdContainer<Vec<TrackData>>,
    id_by_name: HashMap<String, AutomationId>,
}

impl Default for AutomationTimeline {
    #[inline]
    fn default() -> Self {
        Self::new()
    }
}

impl AutomationTimeline {
    #[inline]
    pub fn new() -> Self {
        Self {
            tracks: vec![].into(),
            id_by_name: HashMap::new(),
        }
    }

    /// Registers a new automation parameter with the given name.
    ///
    /// # Panics
    /// Panics if the given name has previously been used to register an id.
    pub fn register(&mut self, name: impl Into<String>) -> AutomationId {
        let id = self.tracks.push_id(TrackData {
            track: AutomationTrack::new(),
        });

        if self.id_by_name.insert(name.into(), id).is_some() {
            panic!("an automation track with the same name already exists");
        }

        id
    }

    pub fn get_track(&self, id: AutomationId) -> Option<&AutomationTrack> {
        self.tracks.get(id.as_index()).map(|t| &t.track)
    }

    pub fn get_track_mut(&mut self, id: AutomationId) -> Option<&mut AutomationTrack> {
        self.tracks.get_mut(id.as_index()).map(|t| &mut t.track)
    }

    pub fn get_id_by_name(&self, name: &str) -> Option<AutomationId> {
        self.id_by_name.get(name).copied()
    }

    /// Queries the value of the automation associated with the given id at the specified
    /// sample offset.
    ///
    /// # Panics
    /// Panics if an automation with the given id doesn't exist. This can only happen if
    /// an id generated by a different timeline is used.
    pub fn query_value(&self, id: AutomationId, sample_offset: u64) -> f32 {
        self.tracks[id].track.query_value(sample_offset)
    }
}
#[cfg(test)]
mod test {
    use crate::id::IncrementalId;

    use super::*;

    #[test]
    fn register_and_get_by_name() {
        let mut timeline = AutomationTimeline::new();

        let volume_id = timeline.register("Volume");
        let pan_id = timeline.register("Pan");

        // Verify they generate distinct IDs
        assert_ne!(volume_id, pan_id);

        // Verify we can fetch the IDs back by their string names
        assert_eq!(timeline.get_id_by_name("Volume"), Some(volume_id));
        assert_eq!(timeline.get_id_by_name("Pan"), Some(pan_id));

        // Verify querying a non-existent track returns None
        assert_eq!(timeline.get_id_by_name("Pitch"), None);
    }

    #[test]
    #[should_panic(expected = "an automation track with the same name already exists")]
    fn register_duplicate_name_panics() {
        let mut timeline = AutomationTimeline::new();

        timeline.register("Cutoff");
        // This second registration should trigger the panic guard
        timeline.register("Cutoff");
    }

    #[test]
    fn get_track_and_mut() {
        let mut timeline = AutomationTimeline::new();
        let id = timeline.register("Filter");

        // Test immutable retrieval
        let track = timeline.get_track(id);
        assert!(
            track.is_some(),
            "Track should exist for a newly registered ID"
        );

        // Test mutable retrieval
        let track_mut = timeline.get_track_mut(id);
        assert!(
            track_mut.is_some(),
            "Mutable track should exist for a newly registered ID"
        );
    }

    #[test]
    fn get_track_invalid_id() {
        let timeline = AutomationTimeline::new();

        let invalid_id = AutomationId::FIRST.next().next().next();

        assert!(timeline.get_track(invalid_id).is_none());
    }

    #[test]
    #[should_panic]
    fn query_value_invalid_id_panics() {
        let timeline = AutomationTimeline::new();
        let invalid_id = AutomationId::FIRST.next().next().next();

        let _ = timeline.query_value(invalid_id, 100);
    }
}
